version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # Optional: Add volume for persistence if needed
    # volumes:
    #   - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount current directory to /app in container for development
      # Allows code changes without rebuilding image
      - .:/app
    environment:
      # Optional: Define environment variables if needed by the app
      # e.g., FLASK_ENV: development
      REDIS_HOST: redis # Service name from this compose file
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy # Wait for Redis to be ready

# Optional: Define named volume for Redis persistence
# volumes:
#   redis_data: 